CREATE TABLE users(
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,

  phone_number TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);